# Generated by Django 6.1 on 2026-08-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='contant of product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price of the product')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
