# Generated by Django 6.1 on 2026-09-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_description_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'الدفع عند الاستلام'), ('card', 'فيزا / ماستركارد'), ('vodafone', 'فودافون كاش')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='vodafone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Paid', 'مدفوع'), ('Shipped', 'تم الشحن'), ('Completed', 'مكتمل'), ('Cancelled', 'ملغي')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phones', 'هواتف'), ('Computers', 'كمبيوتر'), ('Glasses', 'نظارات'), ('Accessories', 'إكسسوارات')], max_length=40),
        ),
    ]
