# Generated by Django 6.1 on 2026-09-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='reset_token_expiration',
            new_name='reset_password_expire',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reset_password_token',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
